# Generated by Django 4.1.4 on 2022-12-29 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecmd',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='bondecmd',
            name='quantite',
        ),
        migrations.AddField(
            model_name='bondecmd',
            name='Fournisseur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bondecmd',
            name='date_b',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Produit_BonDeCmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bondecmd')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
    ]
